### ISSUE TITLE
Need help for the maintenance of this project?

### ISSUE THREAD

**Issue by moufmouf** [ronvanderheijden/openid-connect#21]
Hey @ronvanderheijden ,

Your package is exactly what I needed and I'm using (a fork of) it in production now.
So first of all, thanks for the hard work.

I've noticed you are not maintaining it anymore (I'm not sure you even noticed the 4 PRs I opened :) )

In the case you are seeing this message, do you need help in maintaining it? I'm considering forking it but I would really like to avoid that as much as possible as fragmenting the packages is never a good idea. If you need some help to review the PRs, I'm volunteering to help maintain the package! Let me know!

**Comment by theaungmyatmoe** [comment]
I hope the owner responds back to us, as I am using this package in an abstracted manner to develop OAuth 2.1 + OpenID Connect for our microservices at my startup, @myanmarcyberyouths, and my product, https://breezemm.com.

**Comment by ronvanderheijden** [comment]
Hey guys!

I am glad you like the package, but maintaining it is currently not possible for me. I can look at PRs now and then, but I don't have the time right now to work on new features/bugfixes

@moufmouf , your help as a volunteer/co-maintainer is very welcome! I will give you some permissions to do that, but I would like to be a part of the review process.

Thanks again for your kind words. Let's make the packages up-to-date and better together!

**Comment by moufmouf** [comment]
Thanks a lot! I don't know why, I only noticed your message now.
I'll make my best ;)
We still have #17 and #18 to merge. Shall I wait for your comments or proceed forward?
