### ISSUE TITLE
New Release to packagist.org?

### ISSUE THREAD

**Issue by timcortesi** [ronvanderheijden/openid-connect#24]
I would like to use some of the more recently added features in my project (.well-known routes, etc) but the latest version on packagist (1.1.0) is from over a year ago.

I currently have my project pointed at "dev-main" https://packagist.org/packages/ronvanderheijden/openid-connect#dev-main but that's less than ideal.

Are there plans to push these changes into a new version on packagist?

**Comment by moufmouf** [comment]
Looks good to me.
Since we have new features, I'll tag a new minor version (1.2.0)
@ronvanderheijden  no objections?
