### ISSUE TITLE
openid-configuration scopes_supported is malformed

### ISSUE THREAD

**Issue by timcortesi** [ronvanderheijden/openid-connect#25]
The value of `scopes_supported` as returned by the default endpoint `/.well-known/openid-configuration` violates the spec as outlined here: https://openid.net/specs/openid-connect-discovery-1_0-37.html

**scopes_supported**
RECOMMENDED. **JSON array** containing a list of the [OAuth 2.0](https://openid.net/specs/openid-connect-discovery-1_0-37.html#RFC6749) [RFC6749] scope values that this server supports. 

It should be returning a simple json array of scopes, where as currently it is returning a json object with scopes and descriptions. 

Currently it returns something like:
```json
"scopes_supported": {
    "openid": "Enable OpenID Connect",
    "profile": "Information about your profile",
    "email": "Information about your email address",
    "phone": "Information about your phone numbers",
    "address": "Information about your address"
  }
```

and it should return something like:
```json
"scopes_supported": [
    "openid",
    "profile",
    "email",
    "phone",
    "address"
  ]
```

To correct this, Line 35 of DiscoveryController.php:
```php
            'scopes_supported' => config('openid.passport.tokens_can'),
```
Should be changed to:
```php
            'scopes_supported' => array_keys(config('openid.passport.tokens_can')),
```

**Comment by moufmouf** [comment]
Hey @timcortesi,

Thanks a lot for the report. Looking at this right now!
