### ISSUE TITLE
 ERROR  syntax error, unexpected ')', expecting variable (T_VARIABLE) 

### ISSUE THREAD

**Issue by goldgeer** [ronvanderheijden/openid-connect#30]
ERROR  syntax error, unexpected ')', expecting variable (T_VARIABLE) in vendor/ronvanderheijden/openid-connect/src/IdTokenResponse.php on line 39.

There is a comma symbol beyond the last parameter in constructor .
public function __construct(
        IdentityRepositoryInterface $identityRepository,
        ClaimExtractor $claimExtractor,
        Configuration $config,
        CurrentRequestServiceInterface $currentRequestService = null,
        $encryptionKey = null , <============================== comma
    )

**Comment by ronvanderheijden** [comment]
You are using an outdated PHP version. You should upgrade to a newer version (preferable 8.3).

**Comment by stof** [comment]
this repo should not tell composer it supports PHP 7.4 if it uses a syntax introduced in PHP 8.0 though.

**Comment by ronvanderheijden** [comment]
This is true, but still, PHP 7.4 is not actively supported for almost 3 years.
