### ISSUE TITLE
Error in signature of methods __construct and getBuilder from OpenIDConnect\IdTokenResponse.php

### ISSUE THREAD

**Issue by medina325** [ronvanderheijden/openid-connect#7]
Both methods's last arguments contain a trailing comma in the end that raises an error.

```php
public function __construct(
        IdentityRepositoryInterface $identityRepository,
        ClaimExtractor $claimExtractor,
        Configuration $config,
 )
```
and 
```php
protected function getBuilder(
        AccessTokenEntityInterface $accessToken,
        IdentityEntityInterface $userEntity,
    )
```

After removing the commas, the errors are gone.

**Comment by ronvanderheijden** [comment]
Hi, thank for your time!

Could you provide me with the error message?  And what PHP version are you using?

Trailing comma's in parameter lists should be possible since PHP 8.0.

Thanks again!

**Comment by medina325** [comment]
Using PHP 7.4.14, that's why it raises an error.

**Comment by ronvanderheijden** [comment]
Not going to support PHP 7.4 anymore since it's EOL.
